"""jsonb for the revision journal, indexes on hot foreign keys, role check

revisions.op/inverse были json — сырым текстом без операторов вхождения и без
возможности построить GIN-индекс, хотя все три фичи на этом журнале ищут по
содержимому. Продукт только под Postgres; после появления боевых записей
такая правка стоит переписывания таблицы.

Индексы — по внешним ключам, которые читаются постоянно: memberships.user_id
(на каждом запросе с сессией; составной (org_id, user_id) ведёт не с той
колонки), tasks.project_id и categories.project_id (чтение проекта целиком),
revisions.batch_id (отмена групповой операции).

CHECK на memberships.role: колонка была свободным String(16), и значение вне
Role превращалось в ValueError, то есть в пятисотку, ещё до проверки прав.

Revision ID: 3b3648273b7a
Revises: da03b89192b8
Create Date: 2026-08-10 22:02:49.913585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b3648273b7a'
down_revision: Union[str, Sequence[str], None] = 'da03b89192b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_project_id'), 'categories', ['project_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_check_constraint('ck_memberships_role', 'memberships', "role IN ('owner', 'editor', 'viewer', 'client')")
    op.alter_column('revisions', 'op',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('revisions', 'inverse',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index(op.f('ix_revisions_batch_id'), 'revisions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_revisions_batch_id'), table_name='revisions')
    op.alter_column('revisions', 'inverse',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('revisions', 'op',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint('ck_memberships_role', 'memberships', type_='check')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_categories_project_id'), table_name='categories')
    # ### end Alembic commands ###
