"""email verification tokens

Таблица одноразовых ссылок подтверждения адреса: колонка
users.email_verified_at существовала с самого начала, но заполнить её было
нечем — логики подтверждения не было вовсе.

Устроена как sessions: наружу уходит открытый токен, здесь лежит его хеш.
ondelete=CASCADE — удаление пользователя уносит его неиспользованные ссылки;
индекс по user_id нужен подтверждению и повторной отправке, обе ищут по
владельцу.

Revision ID: 4d44f75a2766
Revises: 3b3648273b7a
Create Date: 2026-08-11 07:51:28.915545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d44f75a2766'
down_revision: Union[str, Sequence[str], None] = '3b3648273b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
