"""share links and comments

Токен публичной ссылки лежит открытым текстом — в отличие от приглашения, и
это осознанная разница: ссылку владелец копирует и пересылает снова и снова, а
хеш означал бы, что «скопировать ещё раз» требует выпустить новую и разослать
всем заново.


Revision ID: 5fc578026054
Revises: 9c584d8968ac
Create Date: 2026-08-11 09:06:12.645393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc578026054'
down_revision: Union[str, Sequence[str], None] = '9c584d8968ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('comments_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_share_links_project_id'), 'share_links', ['project_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('guest_name', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    # clock_timestamp(), а не now(): now() отдаёт время начала транзакции, и
    # две реплики, добавленные одним запросом, становятся неразличимы по
    # времени — лента переставляла бы их местами от запроса к запросу.
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_project_id'), 'comments', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_project_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_share_links_project_id'), table_name='share_links')
    op.drop_table('share_links')
    # ### end Alembic commands ###
