"""undo bookkeeping on revisions

revisions.undoes_seq — номер ревизии, которую эта отменила. Без него
«отменить последнее» отменяло бы собственную отмену: журнал линеен, и после
отмены самая новая запись сверху — это она сама.

Revision ID: 6681178a1115
Revises: 036f4c8b7f36
Create Date: 2026-08-11 08:13:17.876775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6681178a1115'
down_revision: Union[str, Sequence[str], None] = '036f4c8b7f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revisions', sa.Column('undoes_seq', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revisions', 'undoes_seq')
    # ### end Alembic commands ###
