"""ai sessions and llm credentials

AiSession живёт отдельно от проекта, потому что до применения проекта не
существует: AI ничего не пишет в проект без явного подтверждения человека.
Ключ LLM шифруется симметрично секретом приложения — наружу отдаётся только
признак «ключ настроен». tasks.created_by_ai_session_id нужен ради записи
«создана AI-сессией» в истории задачи.

Revision ID: 9c584d8968ac
Revises: 1b744a85e51f
Create Date: 2026-08-11 08:55:01.114673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c584d8968ac'
down_revision: Union[str, Sequence[str], None] = '1b744a85e51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_llm_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('ai_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('draft', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('applied_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_sessions_org_id'), 'ai_sessions', ['org_id'], unique=False)
    op.add_column('tasks', sa.Column('created_by_ai_session_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'ai_sessions', ['created_by_ai_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'created_by_ai_session_id')
    op.drop_index(op.f('ix_ai_sessions_org_id'), table_name='ai_sessions')
    op.drop_table('ai_sessions')
    op.drop_table('org_llm_credentials')
    # ### end Alembic commands ###
