"""share links, comments, per-project access for the client role

Три таблицы публичного доступа (раздел 7 спецификации).

share_links хранит токен открытым текстом, в отличие от приглашений: публичную
ссылку владелец копирует из настроек проекта снова и снова, и сервер, забывший
её, оставил бы единственным способом «показать ещё раз» выпуск новой ссылки.
Частичный уникальный индекс держит инвариант «действующая ссылка у проекта
одна»; отозванных сколько угодно — это журнал того, какой адрес когда умер.

comments: автор — либо участник, либо гость по имени, и ровно один из двух.
Держит это CHECK, а не маршрут: маршрутов, создающих комментарий, уже два.

project_access: проекты, куда позвали роль client. Без неё матрица прав знает
про грант на проект, а выдать его некому.

Revision ID: adee83e4d023
Revises: 3b3648273b7a
Create Date: 2026-08-11 07:54:59.465600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adee83e4d023'
down_revision: Union[str, Sequence[str], None] = '3b3648273b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id')
    )
    op.create_index(op.f('ix_project_access_project_id'), 'project_access', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_access_user_id'), 'project_access', ['user_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('comments_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_share_links_project_id'), 'share_links', ['project_id'], unique=False)
    op.create_index('uq_share_links_active_project', 'share_links', ['project_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('guest_name', sa.String(length=80), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    # clock_timestamp(), а не now(): порядок реплик держится на этой метке, а
    # now() отдаёт одно и то же время всем вставкам одной транзакции.
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(author_user_id, guest_name) = 1', name='ck_comments_single_author'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_project_id'), 'comments', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_project_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index('uq_share_links_active_project', table_name='share_links', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_share_links_project_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_project_access_user_id'), table_name='project_access')
    op.drop_index(op.f('ix_project_access_project_id'), table_name='project_access')
    op.drop_table('project_access')
    # ### end Alembic commands ###
