"""wave 2 security: throttle, ai usage, internal comments, session idle

Revision ID: e604dc58fa04
Revises: 9c584d8968ac
Create Date: 2026-08-13 04:28:06.693125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e604dc58fa04'
down_revision: Union[str, Sequence[str], None] = '9c584d8968ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('throttle_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bucket', sa.String(length=120), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_throttle_events_bucket_at', 'throttle_events', ['bucket', 'at'], unique=False)
    op.create_table('ai_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'day')
    )
    op.add_column('comments', sa.Column('internal', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('sessions', sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'last_used_at')
    op.drop_column('comments', 'internal')
    op.drop_table('ai_usage')
    op.drop_index('ix_throttle_events_bucket_at', table_name='throttle_events')
    op.drop_table('throttle_events')
    # ### end Alembic commands ###
